version: "3"

services:
  activemq:
    container_name: activemq
    build:
      context: .
    image: misterio/activemq:latest
    ports:      
      - "61616:61616"
      - "8161:8161"
    