
# Volumes are not recreated via a up/down cycle so it is safe to do not sepcify external: true
# Sometimes you want to control it better via a external flag
#
volumes:
  zabbix_postgres:    
    #external: true
  zabbix_disk:
    #external: true

services:
  postgres-server:    # The Postgres Database Service
    image: postgres:12.4
    restart: unless-stopped
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: trustn00ne
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    volumes:
      - zabbix_postgres:/var/lib/postgresql/data:rw
    networks:
      - zabbix-network

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:ubuntu-5.0-latest
    restart: unless-stopped
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: trustn00ne
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    ports: 
      - 10051:10051
    volumes:  
      # Volumes for scripts and related files you can add
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro 
      - zabbix_disk:/usr/lib/zabbix
    networks:
      - zabbix-network

# The main Zabbix web UI or interface
# The default username/password credentials for you Zabbix frontend will be:
#Admin,zabbix
  zabbix-web:   
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: trustn00ne
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Rome"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 80:8080
      - 443:8443
    networks:
      - zabbix-network


networks:
  zabbix-network:

