services:
  watchtower:
    # Automatically updates & restarts the containers when they have new versions available
    # https://containrrr.dev/watchtower
    # https://github.com/containrrr/watchtower
    image: containrrr/watchtower
    command: --interval 3  --scope upgrademe
    restart: always
    volumes:
      # Security warning: in order to apply updates, it needs admin access to administer *all* docker containers on the host system
      - /var/run/docker.sock:/var/run/docker.sock      
