version: '3'
services:  
  sonar:
    container_name: ${MISTERIO_INST_PREFIX}_sonar7
    image: sonarqube:7.9.3-community
    restart: unless-stopped
    ports:
      - "$SONAR_PORT:9000"
    ##### Only for socker swarm:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.90"
          memory: 2048M
    # Required because sonar is slow to shutdown and we want to avoid bad shuts
    stop_grace_period: 10m30s
    volumes:
      - "$SONAR_CONTAINER_STORAGE/conf:/opt/sonarqube/conf"      
      - "$SONAR_CONTAINER_STORAGE/extensions:/opt/sonarqube/extensions"
      - "$SONAR_CONTAINER_STORAGE/data:/opt/sonarqube/data"
