version: '3'
# From wordpress side "elasticpress" is needed
volumes:
  elastic_${VOLUME_NAME}:
    
services:
  # Refer https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
  elasticsearch:
    # Try to push elasticpress to 7.x too
    #image: elasticsearch:7.5.0
    image: elasticsearch:6.4.3
    environment:
      - discovery.type=single-node
      # - bootstrap.memory_lock=true
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1      
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped
    volumes:
      - elastic_${VOLUME_NAME}:/usr/share/elasticsearch/data
