version: "2"
# oss-792
# See https://elk-docker.readthedocs.io/#running-with-docker-compose
volumes:
  elk_data:
services:
  elk_stack:
    image: sebp/elk:oss-792
    ports:
      - "5601:5601" # Kibana web interface 
      - "9200:9200" # Elasticsearch JSON interface
      - "5044:5044" # Logstash Beats interface
    volumes:
        - elk-data:/var/lib/elasticsearch 