version: '3'
volumes:
    jenkins_home_disk:

services:
    jenkins:
        build:
            context: .
        image: misterio-jenkins:1.0.0
        volumes:
            - jenkins_home_disk:/var/jenkins_home 
            # Enable docker socket control
            - "/var/run/docker.sock:/var/run/docker.sock"
            # Expose my repos here
            - $HOME/code:/git-repos
        ports:
            - 8080:8080